FROM golang:1.13.9-buster

ENV GOPROXY=https://goproxy.io

RUN mkdir -p /workdir
COPY . /workdir
WORKDIR /workdir
RUN go build -o /demogo -v

#####################################################

FROM centos:7

COPY --from=0 /demogo /demogo

RUN chmod 0777 /demogo
EXPOSE 8080
CMD ["/demogo"]
